### ISSUE TITLE
Need to provide the ability to add extra files (maybe this is happening with packerina)

### ISSUE THREAD

**Issue by pzfreo** [ballerinax/docker#19]
**Description:**
Suppose I have a config file, I need to get it into the docker. In one of the configuration guides it suggested there would be an annotation to do this, but it isn't documented here.

**Suggested Labels:**

**Suggested Assignees:**

**Affected Product Version:**

**OS, DB, other environment details and versions:**    

**Steps to reproduce:**

**Related Issues:**

**Comment by lakwarus** [comment]
Hi Paul,

Following will be the proposal to address this feature.

Introduce new annotations

@docker:CopyFiles{}

Attributes are like bellow
attribute| description| default value
source| source path of the file (in your machine) | current folder
target | target path (inside container) | /home/ballerina/
isBallerinaConf | false

With this we can copy any files into docker image. When we set **isBallerinaConf** true, then docker CMD will formulate like bellow 

CMD ballerina run --config something.toml -s hello_world_k8s_config.balx

**Comment by lakwarus** [comment]
in the current sample 5

service<http:Service> helloWorld bind helloWorldEP {
  	@http:ResourceConfig {
        methods:["GET"],
        path:"/config"
    }
    **getConfig (endpoint outboundEP, http:Request request) {
        http:Response response = {};
        string payload = readFile("./conf/sample.toml", "r", "UTF-8");
        response.setStringPayload("Configs: "+ payload +"\n");
        _ = outboundEP -> respond(response);
    }**
    @http:ResourceConfig {
        methods:["GET"],
        path:"/data"
    }
    getData (endpoint outboundEP, http:Request request) {
        http:Response response = {};
        string payload = readFile("./data/data.txt", "r", "UTF-8");
        response.setStringPayload("Data: "+ payload +"\n");
        _ = outboundEP -> respond(response);
    }
}

we are reading sample.toml as a normal file reading and return the value. This is not the expected behavior if a config copied to docker with **isBallerinaConf**.  When **isBallerinaConf** set we are passing that toml to ballerina run command.  Then we should be able to retrieve relevant config value by suing ballerina **ConfigAPI** 

It should be something like below

config:getAsString (string key, 
                    string default = null) returns (string)
config:getAsChars (string key, 
                   string default = null) returns (char[])
