### ISSUE TITLE
@docker:Config CMD is not working 

### ISSUE THREAD

**Issue by lakwarus** [ballerinax/docker#365]
Tested version: jBallerina 1.1.4
annotation:

@docker:CopyFiles {
    files: [
        { sourceFile: "/tmp/secret.txt", target: "/tmp/secret.txt"}
    ]
}
@docker:Config {
    cmd: "java -jar ${APP} --b7a.config.secret=/tmp/secret.txt"
}

Issue: 
Generated Dockerfile
=================
# Auto Generated Dockerfile
FROM ballerina/jre8:v1

LABEL maintainer="dev@ballerina.io"

RUN addgroup troupe \
    && adduser -S -s /bin/bash -g 'ballerina' -G troupe -D ballerina \
    && apk add --update --no-cache bash \
    && chown -R ballerina:troupe /usr/bin/java \
    && rm -rf /var/cache/apk/*

WORKDIR /home/ballerina

COPY sample.jar /home/ballerina
COPY secret.txt /tmp/secret.txt

EXPOSE  8080
USER ballerina

java -jar sample.jar --b7a.config.secret=/tmp/secret.txt
=============

Missing "CMD " in the last line of the generated Dockerfile. Due to this docker build is not working and ballerina build is hanged

**Comment by anuruddhal** [comment]
Hi @lakwarus 

As per the implementation, user have to provide the `CMD` also in the annotation. This documented in the sample https://github.com/ballerinax/docker/blob/master/samples/sample8/hello_world_cmd_docker.bal#L9 as well. 

Therefore the annotation should be:
```ballerina
@docker:Config {
    cmd: "CMD java -jar ${APP} --b7a.config.secret=/tmp/secret.txt"
}
```
I guess this is done intentionally so that the user can either provide `CMD` or `ENTRYPOINT`.
